# Generated by Django 4.0.6 on 2022-07-21 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRep',
            fields=[
                ('user',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False,
                                      to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=512)),
                ('hotline', models.CharField(max_length=11, unique=True)),
                ('catagory', models.CharField(max_length=16)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('two_factor_auth', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='default_hotel.jpg', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('user',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False,
                                      to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=512)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('emergency_phone', models.CharField(blank=True, max_length=11)),
                ('national_id', models.CharField(max_length=10, unique=True)),
                ('blood_type', models.CharField(max_length=2)),
                ('dob', models.DateField()),
                ('two_factor_auth', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='default_user.jpg', null=True, upload_to='')),
            ],
        ),
    ]
