# Generated by Django 4.0.6 on 2022-07-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveler',
            name='dob',
        ),
        migrations.AddField(
            model_name='traveler',
            name='age',
            field=models.SmallIntegerField(default=18, verbose_name=2),
            preserve_default=False,
        ),
    ]
