# Generated by Django 4.0.6 on 2022-07-23 18:06

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_remove_hotelrep_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelrep',
            name='image',
            field=models.ImageField(blank=True, default='default_hotel.jpg', null=True,
                                    upload_to=pathlib.PureWindowsPath(
                                        'H:/My Drive/CSE347 Project/Vromonkonna/static/images')),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='image',
            field=models.ImageField(blank=True, default='default_user.jpg', null=True,
                                    upload_to=pathlib.PureWindowsPath(
                                        'H:/My Drive/CSE347 Project/Vromonkonna/static/images')),
        ),
    ]
