# Generated by Django 4.0.6 on 2022-08-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_hotelrep_image_alter_traveler_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelrep',
            name='image',
            field=models.ImageField(blank=True, default='default_hotel.jpg', null=True, upload_to='users/'),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='image',
            field=models.ImageField(blank=True, default='default_user.jpg', null=True, upload_to='users/'),
        ),
    ]
