# Generated by Django 4.0.6 on 2022-08-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
