# Generated by Django 4.0.6 on 2022-08-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='comments',
            field=models.IntegerField(default=0),
        ),
    ]
