# Generated by Django 4.0.6 on 2022-08-14 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0007_previewimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previewimage',
            name='id',
        ),
        migrations.AddField(
            model_name='previewimage',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
