# Generated by Django 4.0.6 on 2022-08-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_remove_previewimage_id_previewimage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previewimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='temp/'),
        ),
    ]
