# Generated by Django 4.0.6 on 2022-08-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_alter_previewimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previewimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
