# Generated by Django 4.0.6 on 2022-08-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_alter_previewimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previewimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
