# Generated by Django 4.0.6 on 2022-08-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_alter_previewimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previewimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/'),
        ),
    ]
