# Generated by Django 4.0.6 on 2022-08-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pkgimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='packages/'),
        ),
    ]
