# Generated by Django 4.0.6 on 2022-08-17 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pkg', '0002_alter_pkgimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='hotel',
            new_name='author',
        ),
    ]
