# Generated by Django 4.0.6 on 2022-08-19 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pkg', '0008_package_rating_package_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='traveler',
            new_name='traveler',
        ),
    ]
