# Generated by Django 4.0.6 on 2022-08-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkg', '0010_remove_review_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.CharField(default='', max_length=32),
        ),
    ]
