# Generated by Django 4.0.6 on 2022-08-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkg', '0011_booking_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.CharField(max_length=32),
        ),
    ]
