# Generated by Django 4.0.6 on 2022-08-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkg', '0013_rename_consumer_booking_traveler'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
