# Generated by Django 4.0.6 on 2022-08-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkg', '0014_booking_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='start_date',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
