# Generated by Django 4.0.6 on 2022-08-20 06:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pkg', '0017_remove_booking_start_date_alter_booking_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='start_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='package',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='package',
            name='start_date',
            field=models.DateField(),
        ),
    ]
