# Generated by Django 4.0.6 on 2022-08-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkg', '0019_remove_booking_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
