# Generated by Django 4.0.6 on 2022-08-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkg', '0020_booking_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
